ERROR 2019-04-23 18:15:02,265 [7    ] rver4.Validation.ExtensionGrantValidator - Grant validation error: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'UserManageDbContext'.
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'UserManageDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at UserManage.Authorization.Users.UserRegistrationManager.RegisterAsync(String name, String phone, String emailAddress, String userName, String plainPassword, Boolean isEmailConfirmed) in H:\ABP项目\UserManage\src\UserManage.Core\Authorization\Users\UserRegistrationManager.cs:line 66
   at UserManage.Validator.ExternalValidator.RegisterExternalUserAsync(ExternalAuthUserInfo externalUser) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 166
   at UserManage.Validator.ExternalValidator.ValidateAsync(ExtensionGrantValidationContext context) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 73
   at IdentityServer4.Validation.ExtensionGrantValidator.ValidateAsync(ValidatedTokenRequest request) in C:\local\identity\server4\IdentityServer4\src\Validation\Default\ExtensionGrantValidator.cs:line 75
ERROR 2019-04-23 18:15:02,297 [7    ] Server4.Validation.TokenRequestValidator - Invalid extension grant: invalid_grant, request details: {
  "ClientId": "wechat",
  "GrantType": "custom",
  "Scopes": "api1 openid profile",
  "Raw": {
    "client_id": "wechat",
    "client_secret": "***REDACTED***",
    "grant_type": "custom",
    "auth": "Wechat",
    "code": "Gp_4zZLY1G_-fxs63K7aXo6VJ1_LjXMQQYeAe7cHpD4"
  }
}
ERROR 2019-04-23 18:30:54,234 [6    ] rver4.Validation.ExtensionGrantValidator - Grant validation error: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'UserManageDbContext'.
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'UserManageDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at UserManage.Authorization.Users.UserRegistrationManager.RegisterAsync(String name, String phone, String emailAddress, String userName, String plainPassword, Boolean isEmailConfirmed) in H:\ABP项目\UserManage\src\UserManage.Core\Authorization\Users\UserRegistrationManager.cs:line 66
   at UserManage.Validator.ExternalValidator.RegisterExternalUserAsync(ExternalAuthUserInfo externalUser) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 166
   at UserManage.Validator.ExternalValidator.ValidateAsync(ExtensionGrantValidationContext context) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 73
   at IdentityServer4.Validation.ExtensionGrantValidator.ValidateAsync(ValidatedTokenRequest request) in C:\local\identity\server4\IdentityServer4\src\Validation\Default\ExtensionGrantValidator.cs:line 75
ERROR 2019-04-23 18:30:54,266 [6    ] Server4.Validation.TokenRequestValidator - Invalid extension grant: invalid_grant, request details: {
  "ClientId": "wechat",
  "GrantType": "custom",
  "Scopes": "api1 openid profile",
  "Raw": {
    "client_id": "wechat",
    "client_secret": "***REDACTED***",
    "grant_type": "custom",
    "auth": "Wechat",
    "code": "3Vf5trHXyLgj4RQtM_Z7K3oOnuYcY6BHyuSKd_8T4fc"
  }
}
ERROR 2019-04-23 19:00:58,073 [13   ] rver4.Validation.ExtensionGrantValidator - Grant validation error: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'UserManageDbContext'.
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'UserManageDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at UserManage.Authorization.Users.UserRegistrationManager.RegisterAsync(String name, String phone, String emailAddress, String userName, String plainPassword, Boolean isEmailConfirmed) in H:\ABP项目\UserManage\src\UserManage.Core\Authorization\Users\UserRegistrationManager.cs:line 66
   at UserManage.Validator.ExternalValidator.RegisterExternalUserAsync(ExternalAuthUserInfo externalUser) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 166
   at UserManage.Validator.ExternalValidator.ValidateAsync(ExtensionGrantValidationContext context) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 73
   at IdentityServer4.Validation.ExtensionGrantValidator.ValidateAsync(ValidatedTokenRequest request) in C:\local\identity\server4\IdentityServer4\src\Validation\Default\ExtensionGrantValidator.cs:line 75
ERROR 2019-04-23 19:00:58,120 [13   ] Server4.Validation.TokenRequestValidator - Invalid extension grant: invalid_grant, request details: {
  "ClientId": "wechat",
  "GrantType": "custom",
  "Scopes": "api1 openid profile",
  "Raw": {
    "client_id": "wechat",
    "client_secret": "***REDACTED***",
    "grant_type": "custom",
    "auth": "Wechat",
    "code": "96u-6LIS3UvXILO9oSx085vXrpa_440wtDiHed1BMj8"
  }
}
ERROR 2019-04-23 19:03:56,775 [10   ] rver4.Validation.ExtensionGrantValidator - Grant validation error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at UserManage.Authorization.Users.UserRegistrationManager.RegisterAsync(String name, String phone, String emailAddress, String userName, String plainPassword, Boolean isEmailConfirmed) in H:\ABP项目\UserManage\src\UserManage.Core\Authorization\Users\UserRegistrationManager.cs:line 74
   at UserManage.Validator.ExternalValidator.RegisterExternalUserAsync(ExternalAuthUserInfo externalUser) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 166
   at UserManage.Validator.ExternalValidator.ValidateAsync(ExtensionGrantValidationContext context) in H:\ABP项目\UserManage\src\UserManage.Web.Core\Validator\ExternalValidator.cs:line 73
   at IdentityServer4.Validation.ExtensionGrantValidator.ValidateAsync(ValidatedTokenRequest request) in C:\local\identity\server4\IdentityServer4\src\Validation\Default\ExtensionGrantValidator.cs:line 75
ERROR 2019-04-23 19:03:56,810 [10   ] Server4.Validation.TokenRequestValidator - Invalid extension grant: invalid_grant, request details: {
  "ClientId": "wechat",
  "GrantType": "custom",
  "Scopes": "api1 openid profile",
  "Raw": {
    "client_id": "wechat",
    "client_secret": "***REDACTED***",
    "grant_type": "custom",
    "auth": "Wechat",
    "code": "Q3okgBYYSzuwNOeKynDsqX1HuI6aWCfTA5awdfBVWm0"
  }
}
